version: '3.0'

includes:
  utils: ../scripts/utils.yml

tasks:
  install:
    desc: Installer les fichiers de configuration
    cmds:
      - task: utils:confirm
        vars: { TASK: "les fichiers de configuration" }
      - ./scripts/config-install.sh ${PWD}

  backup-config:
    desc: Sauvegarder les fichiers de configuration existants
    cmds:
      - task: utils:confirm
        vars: { TASK: "les fichiers de configuration (sauvegarde)" }
      - ./scripts/config-backup.sh

  restore-config:
    desc: Restaurer les fichiers de configuration depuis ./config-backup/
    cmds:
      - task: utils:confirm
        vars: { TASK: "la restauration des fichiers de configuration sauvegardés" }
      - cp -f ./config-backup/zshrc.bak ~/.zshrc || echo "⚠️ ./config-backup/zshrc.bak introuvable"
      - cp -f ./config-backup/zsh_aliases.bak ~/.zsh_aliases || echo "⚠️ ./config-backup/zsh_aliases.bak introuvable"
      - cp -f ./config-backup/gitconfig.bak ~/.gitconfig || echo "⚠️ ./config-backup/gitconfig.bak introuvable"
      - cp -f ./config-backup/gitignore.bak ~/.gitignore || echo "⚠️ ./config-backup/gitignore.bak introuvable"
      - mkdir -p ~/.config
      - cp -f ./config-backup/starship.toml.bak ~/.config/starship.toml || echo "⚠️ ./config-backup/starship.toml.bak introuvable"
      - echo "🔄 Restauration terminée."
