# Default values, except $time is moved to the left.
format = """
$time\
$username\
$hostname\
$directory\
$docker_context\
$container\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[docker_context]
format = '[ 🐋 $context]($style) '
only_with_files = true
style = 'blue bold'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']

[container]
format = '[$name](blue dimmed) '

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = '%T'
style = 'bold cyan'

[username]
show_always = true
style_user = 'bold green'
format = '[$user]($style) '